sudo: required
services:
- docker
before_install:
- chmod +x build.sh
- docker build -t gkarthics/influx-additional-db .
script:
- "./build.sh"
env:
  global:
  - secure: VVYOBfHAG28xtbPjGsaeso5o5KsVqrGZ1BpZyuwYdI2WwiP/dk6CTAqzadDXtgpWLdJFkKSkf1uOezl0MrQOWDPmKLx1RbigaaGCiZSDmalA128sIUo2o8WBYeXsJMlT1VyhZWKdR8zPwCJRgoWHFNZn2S8w5lQFuBthIr6mwQgphaV1628tUXZGemDXqYk2ws8xTlP0gOrlMeQm/prI0aW8KPRvvzESkYSTV14S3XnN7r3/EazMmDbKEe0rsLA9jgO6blEeOvuokgHuXHG3eJL9gGalFQFhrT58CT3JaBcEPyTwhVBmcjFKUdt8ANOge1cqSYoMrBGoBX/nockHWfOpqc3CawD9l7UyhhEYX+aVfhqp5umi7YaX9XbWWKlsxNfvatFc0tQg78KCPhUhBtWKV10L1Ux+bkbEAeVoT1dmEEJiUkgq3HfhQNW6VwR2H/joTm+M7Z7sscRDBrPXSf3CfRwSYGlzjjjFk6z8+jCDE+vbx3PMAxvrhbQeRfeXL4Zrlv0GPOexy/YzDqHqE5lcz1eQrsqn6PAk49UnLZNkXggRkpx6ctEQMM3lk+rz5ZbWkdNPRq95f3gvUOLcTnyONpQ0gdz9shiTNFtW0H3Dauw/TdTZXCKlzRMq9ZkuvQlSOUUwM/fAle7uHOBLO0AuE3Sm/IEeBar5H8yU3WY=
  - secure: ELc7tgPsF87abljsAwRcReeK42TETLbHCMSvjlwkU0yUFfA0/+/WNUggsRl0mfGBrzIeSe7kgtej0s7XS7M7Co2o3mhh9hPPiJxukE/stMXlOTf4p7PY3Fg7zuYdUPmxW9iUbkckdLrTdOVOqlT8gQW9kkgxgMfVRAw2CaNCO2tweF0NbN9x6XvOqXTKvaFPYLwGaxryMXf1XLrJIQ0Mcn/Nhy85c5zNzS2VQmnVfnpKR37ONako+kGLf3hrRKjwgfHNqf6A/ewZQYjEh1TvDdkt0eszCfpmFV1U+FHNqmZmmfm5E2zpDvYS6jLyRynPmzNQ8swCh9y2lsx5Y6aBsB+n5w3RKKTLb4VD5lX9A5DHlMkJ7yar/KLETVHl9wC6r6ua8Z+IeVVEjlZTglpDjeZe1wG70qMyYVEn5PSkjA7gH1JELIJ3RE322+OSsNqXYoItTRaYdtsu9UiXkvjgDIhZ6qd0/p6ZK8YjOX4X7NK3g9lFg4KkXf+v3oYxrhQ3Veo/GfMc3wl9+aCcJnIa4HM1pZq4xT7wmqCzjazyeLTexsHQQQ+GwcCi42W/MVrE6jDurC4t+cN0YxPVnfK1Twx4EcJ+16sc6ZRDft5UJ8mnSeh+yM478DCVvNoNkyrYxn1zbFcDuDBYlhHU49h/1tJDrE4G7YNh3h7gFXu8uoY=
